apiVersion: v1
kind: Service
metadata:
  name: {{ include "bar.fullname" . }}
  labels:
    {{- include "bar.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "bar.selectorLabels" . | nindent 4 }}
